In [76]:
# This file is to prepare the data for the district model
# For each block get the following information:

# Block Level Data 

# Electricity Demand 2020
# Electricity Demand 2021
# Electricity Demand 2022
# Gas Demand 2020
# Gas Demand 2021
# Gas Demand 2022
# District Heating Demand 2020
# District Heating Demand 2021
# District Heating Demand 2022
# Population 2020
# Population 2021
# Population 2022
# Relevant GML IDS for the block/district 
# Building Age 

# Building Level Data
# Number of Floors from Alkis file 
# Shape 
# Block ID

In [77]:
# Create Example Block File 
import pandas as pd

In [78]:
building_age = pd.read_csv(r'C:\Users\felix\Programmieren\tecdm\data\berlin\02_Gebäudealter.csv')
building_age.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 29 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   blknr       48 non-null     int64
 1   bez         48 non-null     int64
 2   bezname     48 non-null     object
 3   plr         48 non-null     int64
 4   blktypname  48 non-null     object
 5   ewk         48 non-null     object
 6   area        48 non-null     float64
 7   datum       48 non-null     object
 8   ueberw_dek  36 non-null     object
 9   freistehen  16 non-null     float64
 10  doppelhaus  5 non-null      float64
 11  gereihtes   34 non-null     float64
 12  anderertyp  26 non-null     float64
 13  x_bis_1900  19 non-null     float64
 14  x1901_1910  22 non-null     float64
 15  x1911_1920  22 non-null     float64
 16  x1921_1930  21 non-null     float64
 17  x1931_1940  8 non-null      float64
 18  x1941_1950  7 non-null      float64
 19  x1951_1960  18 non-null     float64
 20  x1961_1970  10 non-null     float64
 21  x1971_1980  7 non-null      float64
 22  x1981_1990  6 non-null      float64
 23  x1991_2000  4 non-null      float64
 24  x2001_2010  2 non-null      float64
 25  x2011_2015  1 non-null      float64
 26  ew2015      35 non-null     float64
 27  typ         36 non-null     float64
 28  typklar     36 non-null     object
dtypes: float64(20), int64(3), object(6)
memory usage: 11.0+ KB

In [79]:
electricity_demand = pd.read_csv(r'C:\Users\felix\Programmieren\tecdm\data\berlin\04_Electricity.csv')
electricity_demand

,fid,blknr,verbrauch_mwh,ausgeschlossen,verbrauch_mwh2020,ausgeschlossen2020,verbrauch_mwh2021,ausgeschlossen2021
0,1,19017,126.159,NaN,120.116,NaN,123.774,NaN
1,2,19033,1275.717,NaN,1091.895,NaN,1264.105,NaN
2,3,19609,21127.807,NaN,19926.378,NaN,20461.183,NaN
3,4,19692,1360.709,NaN,1037.488,NaN,1293.629,NaN
4,5,19708,136.236,NaN,77.141,NaN,87.391,NaN
5,6,19742,5499.234,NaN,5429.684,NaN,5468.668,NaN
6,7,19759,NaN,Der Verbrauch wird aus Datenschutzgründen nich...,NaN,Der Verbrauch wird aus Datenschutzgründen nich...,NaN,Der Verbrauch wird aus Datenschutzgründen nich...
7,8,19760,NaN,Der Verbrauch wird aus Datenschutzgründen nich...,NaN,Der Verbrauch wird aus Datenschutzgründen nich...,NaN,Der Verbrauch wird aus Datenschutzgründen nich...
8,9,19901,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,Keine Angabe zum Verbrauch verfügbar
9,10,20020,NaN,Der Verbrauch wird aus Datenschutzgründen nich...,NaN,Der Verbrauch wird aus Datenschutzgründen nich...,NaN,Der Verbrauch wird aus Datenschutzgründen nich...
10,11,20021,NaN,Der Verbrauch wird aus Datenschutzgründen nich...,NaN,Der Verbrauch wird aus Datenschutzgründen nich...,NaN,Der Verbrauch wird aus Datenschutzgründen nich...
11,12,20022,110.793,NaN,115.702,NaN,117.570,NaN
12,13,20023,173.854,NaN,182.027,NaN,180.491,NaN
13,14,20027,809.294,NaN,843.714,NaN,889.042,NaN
14,15,20028,23.155,NaN,NaN,Der Verbrauch wird aus Datenschutzgründen nich...,NaN,Der Verbrauch wird aus Datenschutzgründen nich...
15,16,20029,259.713,NaN,271.946,NaN,278.195,NaN
16,17,20030,249.643,NaN,261.133,NaN,267.326,NaN
17,18,20035,718.907,NaN,600.774,NaN,651.250,NaN
18,19,20036,496.584,NaN,528.244,NaN,527.903,NaN
19,20,20037,769.582,NaN,800.408,NaN,830.192,NaN
20,21,20038,985.165,NaN,1049.140,NaN,1037.121,NaN
21,22,20039,794.209,NaN,856.029,NaN,870.674,NaN
22,23,20040,612.016,NaN,641.754,NaN,659.479,NaN
23,24,20041,802.906,NaN,1071.922,NaN,1061.345,NaN
24,25,20042,1225.315,NaN,1267.158,NaN,1297.228,NaN
25,26,20043,799.847,NaN,847.864,NaN,839.088,NaN
26,27,20044,943.118,NaN,1049.405,NaN,1024.746,NaN
27,28,20045,642.910,NaN,664.307,NaN,653.944,NaN
28,29,20050,783.397,NaN,845.068,NaN,778.312,NaN
29,30,20051,1284.086,NaN,1370.755,NaN,1327.962,NaN
30,31,20052,671.322,NaN,769.994,NaN,742.087,NaN
31,32,20053,567.885,NaN,573.613,NaN,580.686,NaN
32,33,20054,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,Keine Angabe zum Verbrauch verfügbar
33,34,20055,898.815,NaN,876.964,NaN,887.347,NaN
34,35,20057,263.488,NaN,267.642,NaN,270.802,NaN
35,36,20058,297.397,NaN,310.350,NaN,311.175,NaN
36,37,20059,236.483,NaN,236.602,NaN,243.521,NaN
37,38,20670,771.509,NaN,792.680,NaN,774.847,NaN
38,39,20672,1587.177,NaN,1498.600,NaN,1496.648,NaN
39,40,20673,512.692,NaN,720.537,NaN,676.185,NaN
40,41,20691,774.702,NaN,780.783,NaN,807.293,NaN
41,42,20902,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,Keine Angabe zum Verbrauch verfügbar
42,43,21060,484.546,NaN,627.881,NaN,523.964,NaN
43,44,21061,22965.429,NaN,20972.197,NaN,21042.802,NaN
44,45,21062,2207.921,NaN,2166.994,NaN,2219.293,NaN

In [80]:
# Dictionary for renaming columns
rename_dict_el = {
    'fid': 'fid',
    'blknr': 'blknr',
    'verbrauch_mwh': 'el_consumption_mwh_2022',
    'ausgeschlossen': 'el_excluded_2022',
    'verbrauch_mwh2020': 'el_consumption_mwh_2020',
    'ausgeschlossen2020': 'el_excluded_2020',
    'verbrauch_mwh2021': 'el_consumption_mwh_2021',
    'ausgeschlossen2021': 'el_excluded_2021',
}

# Assuming `df` is your DataFrame
electricity_demand.rename(columns=rename_dict_el, inplace=True)

In [81]:
gas_demand = pd.read_csv(r'C:\Users\felix\Programmieren\tecdm\data\berlin\06_Gas.csv')
gas_demand.columns

Index(['blknr', 'bez', 'bezname', 'plr', 'blktypname', 'ewk', 'area', 'datum',
       'fid', 'verbrauch_', 'ausgeschlo', 'verbrauc_1', 'ausgesch_1',
       'verbrauc_2', 'ausgesch_2'],
      dtype='object')

In [82]:

# Dictionary for renaming columns
# Check which year is what, 2022 can be identified here: https://energieatlas.berlin.de/ 
rename_dict_gas = {
    'fid': 'fid',
    'blknr': 'blknr',
    'verbrauch_': 'gas_consumption_mwh_2022',
    'ausgeschlo': 'gas_excluded_2022',
    'verbrauc_1': 'gas_consumption_mwh_2021',
    'ausgesch_1': 'gas_excluded_2021',
    'verbrauc_2': 'gas_consumption_mwh_2020',
    'ausgesch_2': 'gas_excluded_2020',
    'blknr' : 'blknr',
    'bez' : 'gas_bez',
    'bezname' : 'gas_bezname',
    'plr' : 'gas_plr',
    'blktypname' : 'gas_blktypname',
    'ewk' : 'gas_ewk',
    'area': 'gas_area',
    'datum' : 'gas_datum',
}


# Assuming `df` is your DataFrame
gas_demand.rename(columns=rename_dict_gas, inplace=True)

In [83]:
gas_demand.columns

Index(['blknr', 'gas_bez', 'gas_bezname', 'gas_plr', 'gas_blktypname',
       'gas_ewk', 'gas_area', 'gas_datum', 'fid', 'gas_consumption_mwh_2022',
       'gas_excluded_2022', 'gas_consumption_mwh_2021', 'gas_excluded_2021',
       'gas_consumption_mwh_2020', 'gas_excluded_2020'],
      dtype='object')

In [84]:
# Drop unnecessary columns
gas_demand.drop(columns=['gas_bez', 'gas_bezname', 'gas_plr', 'gas_blktypname', 'gas_ewk', 'gas_area', 'gas_datum'], inplace=True)

In [85]:
dh_demand = pd.read_csv(r'C:\Users\felix\Programmieren\tecdm\data\berlin\05_DistrictHeating.csv')

# Check this 

rename_dict_dh = { 
    'verbrauch_': 'dh_consumption_mwh2022',  
    'verbrauc_1': 'dh_consumption_mwh_2021',
    'verbrauc_2': 'dh_consumption_mwh_2020',
    'blknr': 'blknr',  
    'bez': 'dh_bez',
    'bezname': 'dh_bezname',
    'plr': 'dh_plr',
    'blktypname': 'dh_blktypname',
    'ewk': 'dh_ewk', 
    'area': 'dh_area',
    'datum': 'dh_datum',

}

dh_demand = dh_demand.rename(columns=rename_dict_dh)
dh_demand.columns

Index(['blknr', 'dh_bez', 'dh_bezname', 'dh_plr', 'dh_blktypname', 'dh_ewk',
       'dh_area', 'dh_datum', 'dh_consumption_mwh2022',
       'dh_consumption_mwh_2021', 'dh_consumption_mwh_2020', 'blknr_2',
       'bez_2', 'bezname_2', 'plr_2', 'blktypna_1', 'ewk_2', 'area_2',
       'datum_2'],
      dtype='object')

In [86]:
dh_demand.drop(columns=['dh_bez', 'dh_bezname', 'dh_plr', 'dh_blktypname', 'dh_ewk', 'dh_area', 'dh_datum'], inplace=True)

In [87]:
inhabtiants_2020 = pd.read_csv(r'C:\Users\felix\Programmieren\tecdm\data\berlin\03_Inhabitants2020.csv')
inhabtiants_2021 = pd.read_csv(r'C:\Users\felix\Programmieren\tecdm\data\berlin\03_Inhabitants2021.csv')
inhabtiants_2022 = pd.read_csv(r'C:\Users\felix\Programmieren\tecdm\data\berlin\03_Inhabitants2022.csv')
inhabtiants_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   blknr       45 non-null     int64
 1   bez         45 non-null     int64
 2   bezname     45 non-null     object
 3   plr         45 non-null     int64
 4   blktypname  45 non-null     object
 5   ewk         45 non-null     object
 6   area        45 non-null     float64
 7   datum       45 non-null     object
 8   fid         45 non-null     int64
 9   verbrauch_  33 non-null     float64
 10  ausgeschlo  12 non-null     object
 11  verbrauc_1  37 non-null     float64
 12  ausgesch_1  8 non-null      object
 13  verbrauc_2  37 non-null     float64
 14  ausgesch_2  0 non-null      float64
 15  fid_2       44 non-null     float64
 16  schl5       44 non-null     float64
 17  ew2021      44 non-null     float64
 18  flalle      44 non-null     float64
 19  ew_ha_2021  44 non-null     float64
 20  typklar     44 non-null     object
dtypes: float64(10), int64(4), object(7)
memory usage: 7.5+ KB

In [88]:
inhabtiants_2021.columns

Index(['blknr', 'bez', 'bezname', 'plr', 'blktypname', 'ewk', 'area', 'datum',
       'fid', 'verbrauch_', 'ausgeschlo', 'verbrauc_1', 'ausgesch_1',
       'verbrauc_2', 'ausgesch_2', 'fid_2', 'schl5', 'ew2021', 'flalle',
       'ew_ha_2021', 'typklar'],
      dtype='object')

In [89]:
# keep ew (inhabitans) and blknr
inhabtiants_2020 = inhabtiants_2020[['ew2020', 'blknr']]    
inhabtiants_2021 = inhabtiants_2021[['ew2021', 'blknr']]    
inhabtiants_2022 = inhabtiants_2022[['ew2022', 'blknr']]

In [90]:
list_dfs = [building_age, dh_demand, electricity_demand, gas_demand, inhabtiants_2020, inhabtiants_2021, inhabtiants_2022]

In [91]:
merged_df = list_dfs[0]  # Start with the first DataFrame

for df in list_dfs[1:]:  # Iterate over the rest of the DataFrames
    print(df.info())
    merged_df = pd.merge(merged_df, df, on='blknr', how='inner')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   blknr                    45 non-null     int64
 1   dh_consumption_mwh2022   25 non-null     float64
 2   dh_consumption_mwh_2021  25 non-null     float64
 3   dh_consumption_mwh_2020  26 non-null     float64
 4   blknr_2                  45 non-null     int64
 5   bez_2                    45 non-null     int64
 6   bezname_2                45 non-null     object
 7   plr_2                    45 non-null     int64
 8   blktypna_1               45 non-null     object
 9   ewk_2                    45 non-null     object
 10  area_2                   45 non-null     float64
 11  datum_2                  45 non-null     object
dtypes: float64(4), int64(4), object(4)
memory usage: 4.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   fid                      45 non-null     int64
 1   blknr                    45 non-null     int64
 2   el_consumption_mwh_2022  38 non-null     float64
 3   el_excluded_2022         7 non-null      object
 4   el_consumption_mwh_2020  37 non-null     float64
 5   el_excluded_2020         8 non-null      object
 6   el_consumption_mwh_2021  37 non-null     float64
 7   el_excluded_2021         8 non-null      object
dtypes: float64(3), int64(2), object(3)
memory usage: 2.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   blknr                     45 non-null     int64
 1   fid                       45 non-null     int64
 2   gas_consumption_mwh_2022  33 non-null     float64
 3   gas_excluded_2022         12 non-null     object
 4   gas_consumption_mwh_2021  37 non-null     float64
 5   gas_excluded_2021         8 non-null      object
 6   gas_consumption_mwh_2020  37 non-null     float64
 7   gas_excluded_2020         0 non-null      float64
dtypes: float64(4), int64(2), object(2)
memory usage: 2.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ew2020  45 non-null     float64
 1   blknr   45 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 848.0 bytes
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ew2021  44 non-null     float64
 1   blknr   45 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 848.0 bytes
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ew2022  45 non-null     int64
 1   blknr   45 non-null     int64
dtypes: int64(2)
memory usage: 848.0 bytes
None

In [92]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 57 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   blknr                     48 non-null     int64
 1   bez                       48 non-null     int64
 2   bezname                   48 non-null     object
 3   plr                       48 non-null     int64
 4   blktypname                48 non-null     object
 5   ewk                       48 non-null     object
 6   area                      48 non-null     float64
 7   datum                     48 non-null     object
 8   ueberw_dek                36 non-null     object
 9   freistehen                16 non-null     float64
 10  doppelhaus                5 non-null      float64
 11  gereihtes                 34 non-null     float64
 12  anderertyp                26 non-null     float64
 13  x_bis_1900                19 non-null     float64
 14  x1901_1910                22 non-null     float64
 15  x1911_1920                22 non-null     float64
 16  x1921_1930                21 non-null     float64
 17  x1931_1940                8 non-null      float64
 18  x1941_1950                7 non-null      float64
 19  x1951_1960                18 non-null     float64
 20  x1961_1970                10 non-null     float64
 21  x1971_1980                7 non-null      float64
 22  x1981_1990                6 non-null      float64
 23  x1991_2000                4 non-null      float64
 24  x2001_2010                2 non-null      float64
 25  x2011_2015                1 non-null      float64
 26  ew2015                    35 non-null     float64
 27  typ                       36 non-null     float64
 28  typklar                   36 non-null     object
 29  dh_consumption_mwh2022    26 non-null     float64
 30  dh_consumption_mwh_2021   26 non-null     float64
 31  dh_consumption_mwh_2020   27 non-null     float64
 32  blknr_2                   48 non-null     int64
 33  bez_2                     48 non-null     int64
 34  bezname_2                 48 non-null     object
 35  plr_2                     48 non-null     int64
 36  blktypna_1                48 non-null     object
 37  ewk_2                     48 non-null     object
 38  area_2                    48 non-null     float64
 39  datum_2                   48 non-null     object
 40  fid_x                     48 non-null     int64
 41  el_consumption_mwh_2022   41 non-null     float64
 42  el_excluded_2022          7 non-null      object
 43  el_consumption_mwh_2020   40 non-null     float64
 44  el_excluded_2020          8 non-null      object
 45  el_consumption_mwh_2021   40 non-null     float64
 46  el_excluded_2021          8 non-null      object
 47  fid_y                     48 non-null     int64
 48  gas_consumption_mwh_2022  36 non-null     float64
 49  gas_excluded_2022         12 non-null     object
 50  gas_consumption_mwh_2021  40 non-null     float64
 51  gas_excluded_2021         8 non-null      object
 52  gas_consumption_mwh_2020  40 non-null     float64
 53  gas_excluded_2020         0 non-null      float64
 54  ew2020                    48 non-null     float64
 55  ew2021                    47 non-null     float64
 56  ew2022                    48 non-null     int64
dtypes: float64(33), int64(9), object(15)
memory usage: 21.5+ KB

In [93]:
merged_df.drop_duplicates()

,blknr,bez,bezname,plr,blktypname,ewk,area,datum,ueberw_dek,freistehen,...,fid_y,gas_consumption_mwh_2022,gas_excluded_2022,gas_consumption_mwh_2021,gas_excluded_2021,gas_consumption_mwh_2020,gas_excluded_2020,ew2020,ew2021,ew2022
0,19017,4,Charlottenburg-Wilmersdorf,4300518,Block,unbewohnt,135480.859375,1999/07/12 00:00:00.000,NaN,NaN,...,1,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,NaN,0.0,0.0,0
1,19033,4,Charlottenburg-Wilmersdorf,4300517,Block,1-9 Einwohner,22794.015625,1996/10/11 00:00:00.000,NaN,NaN,...,2,1372.379,NaN,1625.945,NaN,1301.379,NaN,6.0,9.0,9
2,19609,4,Charlottenburg-Wilmersdorf,4300518,Block,unbewohnt,177086.625000,1998/10/08 00:00:00.000,NaN,NaN,...,3,13693.442,NaN,14427.602,NaN,10891.403,NaN,0.0,0.0,0
3,19692,4,Charlottenburg-Wilmersdorf,4300518,Block,unbewohnt,96460.437500,2007/05/21 00:00:00.000,NaN,NaN,...,4,1581.244,NaN,1575.340,NaN,1320.417,NaN,0.0,0.0,0
4,19708,4,Charlottenburg-Wilmersdorf,4300518,Block,10-99 Einwohner,16879.630859,2006/03/10 00:00:00.000,NaN,NaN,...,5,NaN,Der Verbrauch wird aus Datenschutzgründen nich...,224.142,NaN,196.409,NaN,19.0,0.0,21
5,19742,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,183565.937500,2005/02/18 00:00:00.000,2001-2010,2.0,...,6,4864.508,NaN,5671.894,NaN,5325.490,NaN,0.0,3.0,3
6,19742,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,183565.937500,2005/02/18 00:00:00.000,1901-1910,1.0,...,6,4864.508,NaN,5671.894,NaN,5325.490,NaN,0.0,3.0,3
7,19742,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,183565.937500,2005/02/18 00:00:00.000,bis 1900,4.0,...,6,4864.508,NaN,5671.894,NaN,5325.490,NaN,0.0,3.0,3
8,19759,4,Charlottenburg-Wilmersdorf,4300517,Block,unbewohnt,8620.879883,1994/11/24 00:00:00.000,NaN,NaN,...,2,1372.379,NaN,1625.945,NaN,1301.379,NaN,6.0,9.0,9
9,19760,4,Charlottenburg-Wilmersdorf,4300517,Block,unbewohnt,1435.945557,1994/11/24 00:00:00.000,NaN,NaN,...,8,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,NaN,0.0,0.0,0
10,19901,4,Charlottenburg-Wilmersdorf,4300518,Bahnblock,unbewohnt,25851.810547,1994/11/24 00:00:00.000,NaN,NaN,...,4,1581.244,NaN,1575.340,NaN,1320.417,NaN,0.0,0.0,0
11,20020,4,Charlottenburg-Wilmersdorf,4300517,Block,unbewohnt,4897.128906,1994/11/24 00:00:00.000,NaN,NaN,...,11,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,NaN,0.0,0.0,0
12,20021,4,Charlottenburg-Wilmersdorf,4300517,Block,unbewohnt,5655.184570,1994/11/24 00:00:00.000,1901-1910,NaN,...,12,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,NaN,0.0,823.0,0
13,20022,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,4956.509277,1994/11/24 00:00:00.000,1931-1940,NaN,...,13,NaN,Der Verbrauch wird aus Datenschutzgründen nich...,NaN,Der Verbrauch wird aus Datenschutzgründen nich...,NaN,NaN,243.0,240.0,222
14,20023,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,6848.019531,1994/11/24 00:00:00.000,1951-1960,NaN,...,14,34.491,NaN,57.911,NaN,43.370,NaN,233.0,222.0,235
15,20027,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,14053.184570,1993/06/30 00:00:00.000,1921-1930,1.0,...,15,1266.009,NaN,1489.637,NaN,1307.496,NaN,730.0,715.0,723
16,20028,4,Charlottenburg-Wilmersdorf,4300517,Block,10-99 Einwohner,3348.633789,1994/10/19 00:00:00.000,NaN,NaN,...,16,NaN,Der Verbrauch wird aus Datenschutzgründen nich...,306.858,NaN,264.726,NaN,9.0,9.0,9
17,20029,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,6372.918457,1993/06/30 00:00:00.000,1921-1930,NaN,...,17,82.095,NaN,74.860,NaN,74.740,NaN,321.0,321.0,318
18,20030,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,6492.959961,2003/06/18 00:00:00.000,1921-1930,NaN,...,18,38.353,NaN,40.327,NaN,38.129,NaN,309.0,299.0,307
19,20035,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,18004.087891,1993/06/30 00:00:00.000,1921-1930,NaN,...,19,13.602,NaN,14.219,NaN,14.657,NaN,217.0,206.0,205
20,20036,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,14272.669922,1993/06/30 00:00:00.000,1921-1930,1.0,...,20,70.979,NaN,69.038,NaN,72.508,NaN,647.0,624.0,647
21,20037,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,11607.428711,1993/06/30 00:00:00.000,1951-1960,1.0,...,21,73.822,NaN,80.596,NaN,47.828,NaN,647.0,669.0,642
22,20038,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,10734.874023,1993/06/30 00:00:00.000,gemischte Baualtersklasse,5.0,...,22,782.158,NaN,889.491,NaN,831.305,NaN,654.0,636.0,621
23,20039,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,13377.912109,1993/06/30 00:00:00.000,1901-1910,1.0,...,23,2483.888,NaN,2769.789,NaN,2343.994,NaN,595.0,586.0,570
24,20040,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,8999.685547,1993/11/10 00:00:00.000,1901-1910,2.0,...,24,2382.602,NaN,2719.693,NaN,2249.042,NaN,472.0,465.0,440
25,20041,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,9360.779297,1993/11/10 00:00:00.000,1901-1910,1.0,...,25,1562.321,NaN,1747.932,NaN,1609.188,NaN,514.0,482.0,497
26,20042,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,17651.447266,1993/07/01 00:00:00.000,1901-1910,NaN,...,26,3623.015,NaN,4322.805,NaN,3629.244,NaN,963.0,925.0,945
27,20043,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,15406.279297,1993/07/01 00:00:00.000,1901-1910,3.0,...,27,3314.817,NaN,3976.071,NaN,3443.750,NaN,622.0,625.0,691
28,20044,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,11569.536133,1993/07/01 00:00:00.000,1901-1910,NaN,...,28,2978.505,NaN,3125.460,NaN,2823.442,NaN,707.0,684.0,658
29,20045,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,10011.813477,1993/06/30 00:00:00.000,1901-1910,NaN,...,29,508.709,NaN,591.024,NaN,523.574,NaN,450.0,437.0,464
30,20050,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,7815.945312,1994/06/01 00:00:00.000,bis 1900,NaN,...,30,1185.914,NaN,1317.958,NaN,1281.116,NaN,491.0,514.0,503
31,20051,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,21565.632812,1997/08/20 00:00:00.000,bis 1900,1.0,...,31,1839.858,NaN,2115.573,NaN,1810.827,NaN,938.0,895.0,910
32,20052,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,10858.265625,1994/06/01 00:00:00.000,1901-1910,NaN,...,32,897.919,NaN,960.467,NaN,857.574,NaN,488.0,488.0,473
33,20053,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,10324.307617,1994/06/01 00:00:00.000,gemischte Baualtersklasse,2.0,...,33,1089.119,NaN,1247.674,NaN,1094.032,NaN,469.0,435.0,446
34,20054,4,Charlottenburg-Wilmersdorf,4300518,Block,unbewohnt,8621.159180,1994/06/01 00:00:00.000,NaN,NaN,...,34,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,NaN,0.0,NaN,0
35,20055,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,77514.328125,1994/11/24 00:00:00.000,1901-1910,NaN,...,35,814.453,NaN,919.874,NaN,837.423,NaN,473.0,0.0,451
36,20057,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,6223.313965,1994/06/01 00:00:00.000,1921-1930,NaN,...,36,4.298,NaN,4.937,NaN,4.277,NaN,273.0,270.0,277
37,20058,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,5485.676758,1994/06/01 00:00:00.000,1921-1930,NaN,...,37,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,NaN,372.0,363.0,374
38,20059,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,12303.541992,1994/06/01 00:00:00.000,1921-1930,1.0,...,38,25.256,NaN,16.551,NaN,16.763,NaN,206.0,215.0,216
39,20670,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,43202.726562,1993/06/30 00:00:00.000,1951-1960,NaN,...,39,974.638,NaN,1786.490,NaN,950.450,NaN,65.0,407.0,73
40,20670,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,43202.726562,1993/06/30 00:00:00.000,1921-1930,NaN,...,39,974.638,NaN,1786.490,NaN,950.450,NaN,65.0,407.0,73
41,20672,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,13669.580078,1995/08/02 00:00:00.000,1981-1990,2.0,...,40,4.740,NaN,5.752,NaN,5.948,NaN,486.0,424.0,444
42,20673,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,12674.413086,1994/10/19 00:00:00.000,1951-1960,2.0,...,41,692.643,NaN,834.961,NaN,721.390,NaN,248.0,244.0,253
43,20691,4,Charlottenburg-Wilmersdorf,4300517,Block,100-999 Einwohner,34357.222656,1994/11/24 00:00:00.000,1901-1910,NaN,...,42,68.266,NaN,70.735,NaN,78.908,NaN,826.0,823.0,815
44,20902,4,Charlottenburg-Wilmersdorf,4300517,Bahnblock,unbewohnt,44769.953125,1994/11/24 00:00:00.000,1901-1910,NaN,...,5,NaN,Der Verbrauch wird aus Datenschutzgründen nich...,224.142,NaN,196.409,NaN,19.0,0.0,21
45,21060,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,15312.609375,1993/07/01 00:00:00.000,1901-1910,NaN,...,44,525.897,NaN,583.877,NaN,509.743,NaN,285.0,280.0,274
46,21061,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,130373.609375,2003/06/18 00:00:00.000,2011-2015,NaN,...,45,NaN,Der Verbrauch wird aus Datenschutzgründen nich...,788.734,NaN,1315.276,NaN,186.0,181.0,195
47,21062,4,Charlottenburg-Wilmersdorf,4300518,Block,100-999 Einwohner,26549.175781,1994/11/24 00:00:00.000,NaN,NaN,...,46,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,Keine Angabe zum Verbrauch verfügbar,NaN,NaN,168.0,166.0,175

In [94]:
merged_df.to_csv(r'C:\Users\felix\Programmieren\tecdm\data\berlin\merged.csv', index=False)